disable currently unused field for `File` as it causes error
- not sure why
  ```
     Error: File.originalSourceUrl provided incorrect OutputType: 'String'
   ``` 